http: null
  # listen: 80
https:
  listen: 443
  generate_keys: true
  private_key: "/etc/homedns/server.pem"
  public_key: "/etc/homedns/server.crt"
  # listen: 80
no_auth: # skip authentication, allow unauthenticated access to REST API
  enabled: false
jwt_auth: # JWT authentication options
  enabled: true
  # asymmetric encryption is best and the default (RS256)
  # a key pair must exist between the server and client
  algorithms: ["RS256"]
  # secrets_path = Secrets will be stored here, they can be generated via CLI `homedns-jks` --help`
  subjects: "/etc/homedns/jwt_secrets/jwt_subjects.yaml"
  issuer: "homedns-clients"  # the clients issuer 'iss' must match
  audience: ["homedns-api"]  # the clients audience 'aud' must match
  leeway: 5  # seconds allowed between signing and the server validating the jwt token
  options:  # you can turn off validation of various fields
    verify_exp: true  # verify expiry
    verify_nbf: true  # verify not before time
    verify_aud: true  # verify audience
    verify_iss: true  # verify issuer
basic_auth:
  enabled: false
  # secrets_path: "/etc/homedns/auth_secrets.json"  # key/value pairs of user: secret
  # hash: "sha256"
dns: # DNS Server settings
  listen_tcp: 53
  listen_udp: 53
  cache: # cache requests
    enabled: true
  forwarding:  # forward requests for unknown domains
    enabled: true
    servers: ["208.67.222.222", "208.67.220.220"]  # can be ip-address, or ip-address:port
    timeouts: [1, 3, 11, 30]  # number of retries and timeouts for each
    # Google         8.8.8.8          8.8.4.4
    # Control D 	 76.76.2.0        76.76.10.0
    # Quad9          9.9.9.9          149.112.112.112
    # OpenDNS Home 	 208.67.222.222   208.67.220.220
    # Cloudflare 	 1.1.1.1          1.0.0.1
    # AdGuard DNS 	 94.140.14.14     94.140.15.15
    # CleanBrowsing  185.228.168.9    185.228.169.9
    # Alternate DNS  76.76.19.19      76.223.122.150
  database:
    sqlite:
      path: "/etc/homedns/records.sqlite"
  tld: 300 # how long records are valid for by default (never set lower than 30 seconds)
  verbosity: 2 # 0 = no logging, 1 = basic dns logging,  2 = full dns query logging